### ISSUE TITLE
Automated generation of content

### ISSUE THREAD

**Issue by brunomateus** [UPHF/FAMAZOA#5]
Create script to generate the new version of the website according to the new version of the dataset

- [x] Get new applications using our crawler
- [x] Update list of repositories
- [x] Update status of each repository (online or offline)
- [ ] Update boxplot
- [x] Update version number and number of applications used in other parts of the website
- [ ] Update details of each application

**Comment by martinezmatias** [comment]
Great I like it! in the short future,  we should do a short paper (tech-report) and put on arxiv
